# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 77cdbb6d22407200e4aa47b1afdc6e326516f2b29d092431a6d99f28b55917816b306a30068ea8c9cfbc9f50c70d226ae8e71ead78522e65290abfbb88e91e5a

test:
  secret_key_base: 8daedb0e2190eac4d9560f4917298f202490024074f5abe3e8a0c12f4f7857d15ded4100a585f1b054862ebb04835bedf73e1156f8620c8c9a4846c09b94565a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
